# Generated by Django 5.2.7 on 2026-01-07 09:20

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openalex_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('title', models.TextField()),
                ('abstract', models.TextField(blank=True, default='')),
                ('doi', models.CharField(blank=True, default='', max_length=255)),
                ('url', models.URLField(blank=True, default='')),
                ('venue', models.CharField(blank=True, default='', max_length=255)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('authors_text', models.TextField(blank=True, default='')),
                ('authors_json', models.JSONField(blank=True, default=list)),
                ('concepts', models.JSONField(blank=True, default=list)),
                ('cited_by_count', models.IntegerField(default=0)),
                ('references_count', models.IntegerField(default=0)),
                ('is_open_access', models.BooleanField(default=False)),
                ('oa_status', models.CharField(blank=True, default='', max_length=32)),
                ('oa_url', models.URLField(blank=True, default='')),
                ('relevance_score', models.FloatField(blank=True, null=True)),
                ('fetched_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-cited_by_count'],
            },
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_token', models.CharField(default=uuid.uuid4, editable=False, max_length=64, unique=True)),
                ('manage_token', models.CharField(default=uuid.uuid4, editable=False, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('query_name', models.CharField(max_length=255)),
                ('abstracts', models.JSONField(blank=True, default=list)),
                ('keywords', models.JSONField(blank=True, default=list)),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_token', models.CharField(max_length=64, unique=True)),
                ('consent_given_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('frequency', models.CharField(choices=[('weekly', 'Weekly')], default='weekly', max_length=16)),
                ('last_sent_at', models.DateTimeField(blank=True, null=True)),
                ('subscriber', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='api.subscriber')),
            ],
            options={
                'unique_together': {('email', 'query_name')},
            },
        ),
        migrations.CreateModel(
            name='GoodMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_id', models.CharField(db_index=True, max_length=255)),
                ('title', models.TextField(blank=True)),
                ('openalex_url', models.URLField(blank=True)),
                ('score', models.FloatField(blank=True, null=True)),
                ('first_clicked_at', models.DateTimeField(auto_now_add=True)),
                ('last_clicked_at', models.DateTimeField(auto_now=True)),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='good_matches', to='api.subscriber')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.subscription')),
            ],
            options={
                'indexes': [models.Index(fields=['work_id'], name='api_goodmat_work_id_1e83fe_idx')],
                'unique_together': {('subscriber', 'subscription', 'work_id')},
            },
        ),
    ]
