# Generated by Django 5.2.7 on 2026-01-07 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SentWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_id', models.CharField(db_index=True, max_length=255)),
                ('sent_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_works', to='api.subscriber')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_works', to='api.subscription')),
            ],
            options={
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['subscriber', 'sent_at'], name='api_sentwor_subscri_ef6f24_idx'), models.Index(fields=['subscription', 'sent_at'], name='api_sentwor_subscri_4f00e2_idx'), models.Index(fields=['work_id'], name='api_sentwor_work_id_546818_idx')],
                'unique_together': {('subscription', 'work_id')},
            },
        ),
    ]
